# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/digital_twin.xdc

# IP: ip/DRAM_BRAM/DRAM_BRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DRAM_BRAM || ORIG_REF_NAME==DRAM_BRAM} -quiet] -quiet

# IP: ip/pll_1/pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] -quiet
